name: typing-tests

on:
  pull_request:
    branches:
      - main
    paths:
      - confluent_kafka-stubs/**/*
      - tests/**/*

jobs:
  typing-tests:
    name: "run: mypy | pyright"
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        poetry-version: ["1.5.1"]
        test-type: ["mypy", "pyright"]
        os: ["ubuntu-latest", "macos-latest"]
        arch: ["x64"] # "arm64" temp switch off, too many trouble with it
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
      - name: prepare pipx, poetry and dependencies
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath
          pipx install poetry=="${poetry_version}"
          poetry install
          poetry show
        env:
          poetry_version: ${{ matrix.poetry-version }}
      - name: run mypy
        if: ( ${{ env.test_type == 'mypy' }} && (${{ matrix.arch != 'arm64' }} && ${{ matrix.python-version == '3.8' }}) )
        run: |
          poetry run mypy --version
          poetry run mypy confluent_kafka-stubs
        env:
          test_type: ${{ matrix.test-type }}
      - name: run pyright
        if: ( ${{ env.test_type == 'pyright' }} && (${{ matrix.arch != 'arm64' }} && ${{ matrix.python-version == '3.8' }}) )
        run: |
          poetry run pyright --version # dry run & install
          poetry run pyright confluent_kafka-stubs
        env:
          test_type: ${{ matrix.test-type }}
